### ISSUE TITLE
How to make skid left with this layout manager

### ISSUE THREAD

**Issue by raj123456789123456789** [DingMouRen/LayoutManagerGroup#1]
hi this is a very good layout manger but i want to know how i can set horizontal scrolling to left with skidlayoutmanger rest everything is great.

**Comment by DingMouRen** [comment]
hi   you can refer to the source code for SkidRightLayoutManager

**Comment by DingMouRen** [comment]
@raj123456789123456789  hi you can refer to the source code for SkidRightLayoutManager

**Comment by raj123456789123456789** [comment]
HI i have tried changing rightskid to left skid but i'm not able to do so
but if you can tell me what changes i should make.
please if you tell me i would be grateful to you because i really need it.
I have been working on this for weeks now please if you could tell me know..

**Comment by raj123456789123456789** [comment]
Hi DingMouRen please can you tell me how 8 can make leftskid layout manager because i really need this i have tried every possible way to make changes but as you have made it you know how to make changes please i really need this with leftskid layout manager..

**Comment by raj123456789123456789** [comment]
Hi @DingMouRen  please if you could tell me how i can change rightskid layout manager to leftskid layout manager i would be really grateful because this is quite important to me.

**Comment by DingMouRen** [comment]
@raj123456789123456789  你去参考这个https://github.com/leochuan/ViewPagerLayoutManager ，没有现成的开源库供你使用的，你要学会自己修改开源库。

**Comment by raj123456789123456789** [comment]
@DingMouRen the library you suggested is very good but your skid layout manager is what i need but with scrolling on left side please if you can add a leftskidlayout manager or you can tell me where i can make changes to do the same because i have been trying for long with no success so please if you can help me out.
Thank you

**Comment by raj123456789123456789** [comment]
Hi DingMouRen please could you tell me how i can change it to leftskid layout manager

**Comment by DingMouRen** [comment]
@raj123456789123456789  Hello, I would like to help you very much, but I am busy working and working overtime every day, I really have no time to expand. It is recommended that you solve the problem by reading the source code.

**Comment by raj123456789123456789** [comment]
Hii @DingMouRen i understand that and i appreciate for your response but
could you tell me where i should make changes to reverse the entire
cardstack with scroll because i tried every code but i dont know how scroll
position is being controlled and how card look is give.
Could you tell me where i should make changes and what kind of..
Thank you

**Comment by raj123456789123456789** [comment]
Hi actually could you refer me an engliah website which teaches this custom
layout manager because google couldnt translate the website you suggested

**Comment by daiji168** [comment]
Should you implement horizontal scrolling to left? I also need now
