### ISSUE TITLE
ViewPagerLayoutManager

### ISSUE THREAD

**Issue by magical-xu** [DingMouRen/LayoutManagerGroup#10]
layoutManager 设置 监听的时候  onPageSelected  和  onLayoutComplete  为什么都是  playVideo(0) ?
不是要根据位置去播视频吗  还有为什么这两个回调都要去播？ 没太看明白，求指点

**Comment by DingMouRen** [comment]
关键是reccylerView.getChildCount(),可见的Item,你可以打印日志去研究一下，

**Comment by elileo1** [comment]
如何做上拉加载更多，有加载的界面提示

**Comment by DingMouRen** [comment]
@elileo1  看一下代码，兄弟，onPageSelected （int position,boolean  isBottom）,很容易理解吧

**Comment by elileo1** [comment]
像PullRefresh那种效果啊， onPageSelected里面能监听到最后一个，但是无法加入加载效果在底部

**Comment by elileo1** [comment]
类似抖音那种加载更多是不是要， 监听到如果是最后一个Item的时候， 对整个RecycleView做上滑动
