### ISSUE TITLE
ViewPagerLayoutManager 

### ISSUE THREAD

**Issue by fccaikai** [DingMouRen/LayoutManagerGroup#12]
抖音效果往上翻页时，会出现同时播放两个视频

**Comment by lilijintao** [comment]
onLayoutComplete()回调方法里把palyVideo删了，不过这样又有一个新问题，首次进入的时候不会播放。

**Comment by fccaikai** [comment]
@lilijintao 只能手动去触发播放第一个视频了

**Comment by DingMouRen** [comment]
兄弟们，LayoutManager只提供怎么展示 Item的，关于视频相关的，需要你们自己控制，比如选择哪个第三方库，提供出来的接口，你们可以使用也可以不使用，也可以自己去扩展接口

**Comment by fccaikai** [comment]
额，只是感觉做demo也要完善，能做到没问题最好。 这个就是用RecyclerView实现ViewPager的效果，用RecyclerView+ PagerSnapHelper就可以实现了。

**Comment by DingMouRen** [comment]
@fccaikai  提供出来的接口，你们可以使用也可以不使用,我不知道你理解到哪里去了，兄弟，ViewPagerLayoutManager有提供接口的，根据需求使用，我实在不知道你理解到哪里去了~~~
