### ISSUE TITLE
添加依赖出错

### ISSUE THREAD

**Issue by Leonidas-Li** [DingMouRen/LayoutManagerGroup#14]
作者您好，我今天使用您的LayoutManagerGroup时，添加com.github.DingMouRen:LayoutManagerGroup:643fb71c8e这个依赖使用不了，请问一下是这个远程的库已经不存在了吗？

**Comment by DingMouRen** [comment]
@Leonidas-Li  不好意思，你在刷新一下，就可以看到新的地址了，implementation 'com.github.DingMouRen:LayoutManagerGroup:1e6f4f96eb'  这个

**Comment by Leonidas-Li** [comment]
好的，谢谢钉大神。

**Comment by Leonidas-Li** [comment]
大神，这个地址还是不行。
