### ISSUE TITLE
请教一下，SkidRightLayoutManager如何获取当前最前方的那个item的postion？

### ISSUE THREAD

**Issue by cjztool** [DingMouRen/LayoutManagerGroup#36]
请教一下，SkidRightLayoutManager如何获取到当前最前方的那个item的postion？我尝试把局部变量bottomItemPosition抛出来，发现这个值会少一个边界值（比如有20条数据，这个postion只从1增加到19，到不了20）请教丁总 有其他方法吗？

**Comment by cjztool** [comment]
有木有个合适的时机监听当前是哪个item在最前方呢？ 之前的方法很不准啊

**Comment by cjztool** [comment]
好吧，，我把SkidRightSnapHelper的findSnapView方法里的
`int pos = ((SkidRightLayoutManager) layoutManager).getFixedScrollPosition(
                    mDirection, mDirection != 0 ? 0.8f : 0.5f);`
pos抛出来了，

**Comment by 15901316237** [comment]
如何取到当前显示的position啊

**Comment by Daniel0225** [comment]
> 找到个方式 非常稳定 恨自己太蠢。。。。

是哪个方式呀

**Comment by lianjf646** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xxd6772123** [comment]
> 哪个方式呀



> 找到个方式 非常稳定 恨自己太蠢。。。。

求解
