### ISSUE TITLE
大佬  求指点啊

### ISSUE THREAD

**Issue by KenStive** [DingMouRen/LayoutManagerGroup#8]
最近在做浏览器多标签功能 （类似UC浏览器多标签）我想借鉴EchelonLayoutManager这个用来做  但是发现往下拉的时候 第二个item 遮住后面的第三个item有点多了 我想让后面item 多漏出来一点 方便点击 请问具体改哪里？在线等 急。。。

**Comment by DingMouRen** [comment]
@KenStive  代码中有item上下间距的字段，自己改下算法就好了
